version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./application:/var/www/html
  nginx:
    image: nginx
    volumes:
      - ./application:/var/www/html
      - ./nginx/application.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8100:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
